CC = g++
CCFLAGS = -O3 -funroll-loops -ffast-math -fomit-frame-pointer -fopenmp
LDFLAGS = -lglut -lGLU -lGL
FILES = ColorScale.cpp ParticleAdvection.cpp LatticeSite.cpp LatticeBoltzmann.cpp Main.cpp

lbdemo: $(FILES)
	$(CC) $(CCFLAGS) -o lbdemo $(FILES) $(LDFLAGS)

clean:
	rm lbdemo

